version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: eatnshare-db
    ports:
      - 20001:5432
    environment:
      - POSTGRES_USER=eatnshare
      - POSTGRES_PASSWORD=eatnshare
      - POSTGRES_DB=eatnshare
    volumes:
      - eatnshare-db-vol:/var/lib/postgresql/data
  backend:
    build: .
    image: xploitedd/eatnshare-backend
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgresql://eatnshare:eatnshare@database:5432/eatnshare?schema=public

volumes:
  eatnshare-db-vol: